global using System;
global using System.Collections;
global using System.ComponentModel;
global using System.Globalization;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Windows;
global using System.Windows.Input;
global using Avalonia;
global using Avalonia.Data.Converters;
global using Avalonia.Controls;
global using Avalonia.Controls.Primitives;
global using Avalonia.Media;
global using Avalonia.Styling;
global using Avalonia.Input;
global using Avalonia.Data;
global using Avalonia.Markup.Xaml.Templates;
global using ReactiveUI;

